default: &default
  adapter: postgresql
  encoding: utf8
  pool: 5
  username: maxirino
  password: maxirino
  timeout: 5000

development:
  <<: *default
  database: maxirino_development

test:
  <<: *default
  database: maxirino_test

production:
  <<: *default
  database: maxirino_production
